### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by ghost** [martinwu42/typeset#2]
how to use the typeset?

**Comment by woct0rdho** [comment]
Sorry that I didn't write docs yet...
You can run the script in command line. The basic usage is:
`python3 typeset.py -i IN_FILENAME -o OUT_FILENAME`
Run `python3 typeset.py --help` to see other arguments.

**Comment by ghost** [comment]
i try run `python3 typeset.py -i in_filename -o out_filename` , but it does not work, there is no one space between number and Chinese.

**Comment by woct0rdho** [comment]
You can add the argument `--minor_space " "`. By default it's empty. I've updated helper strings in the code now.
